name: flutter_release_x
description: A CLI tool to easily build, release, and share Flutter apps. Supports cloud uploads, QR codes, and download links for fast distribution.
version: 0.4.0
repository: https://github.com/RittikSoni/Flutter-Release-X
license: MIT
homepage: https://github.com/RittikSoni/Flutter-Release-X
documentation: https://frx.elpisverse.com
issue_tracker: https://github.com/RittikSoni/Flutter-Release-X/issues

platforms:
  linux:
  windows:
  macos:

screenshots:
  - description: "Flutter Release X Logo"
    path: assets/frx_logo.jpg
  - description: "Flutter Release X (frx) Logo"
    path: assets/frx_gif_banner.gif

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  dio: ^5.9.0
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  http: ^1.6.0
  http_parser: ^4.1.2
  image: ^4.5.4
  path: ^1.9.1
  qr: ^3.0.2
  yaml: ^3.1.3
  crypto: ^3.0.7

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0

funding:
  - https://buymeacoffee.com/kingrittik

# https://dart.dev/tools/pub/pubspec#executables
executables:
  frx: flutter_release_x
  flutter_release_x:

keywords:
  - flutter
  - release
  - share
  - quick
  - cli
  - apk
  - ios
  - windows
  - cloud
  - google-drive
  - aws
  - diawi
  - gitlab
  - microsoft-teams
  - google-playstore
  - app-store
  - aab
  - github
  - aab
  - publish
  - deploy
  - build
  - qr-code
  - automation
  - ci/cd
  - pipeline
  - flutter-release-x

topics:
  - flutter
  - release
  - share-cloud
  - qr-code
  - app-distribution
